### ISSUE TITLE
футпринты транзисторов

### ISSUE THREAD

**Issue by andykarpov** [UzixLS/zx-sizif-512#1]
поменять бы, если можно, где ноги не так близко друг к другу :)

**Comment by UzixLS** [comment]
На алиэкспрессе все BC547/BC549 с обычным, не широким футпринтом. Если поменять футпринт на плате, то придётся заниматься выгибанием ног. Зачем?)

**Comment by UzixLS** [comment]
К тому же широкие 2SA1175 (которые в ревизии D на клавиатуре) в принципе не влезут на плату.

**Comment by andykarpov** [comment]
![image](https://user-images.githubusercontent.com/147979/104837367-afb67b80-58bc-11eb-9593-27d897050a67.png)

Я про такой футпринт

**Comment by andykarpov** [comment]
> К тому же широкие 2SA1175 (которые в ревизии D на клавиатуре) в принципе не влезут на плату.

А у 1175 ноги и так выгнуты с завода так, что совпадают с КТ361 практически :)

**Comment by andykarpov** [comment]
> На алиэкспрессе все BC547/BC549 с обычным, не широким футпринтом. Если поменять футпринт на плате, то придётся заниматься выгибанием ног. Зачем?)

меньше шансов соплю повесить между ногами при монтаже :)

**Comment by UzixLS** [comment]
> Я про такой футпринт
> меньше шансов соплю повесить между ногами при монтаже :)

Ок, принято. Будет в ревизии D1.

> А у 1175 ноги и так выгнуты с завода так, что совпадают с КТ361 практически :)

Не у всех. У меня такие https://aliexpress.ru/item/32510168613.html
КМК, вряд ли на их место просто так влезет какой-то больший футпринт:
![1](https://user-images.githubusercontent.com/1556813/104837615-c661d000-58c6-11eb-8a92-c79536b6b0fe.png)

**Comment by UzixLS** [comment]
Закрыто коммитом 62a8de51fe858cffeb6807d12b4b5533df3119da
