### ISSUE TITLE
Looks like one connection is missing in the PCB Editor?

### ISSUE THREAD

**Issue by AmiManga** [UzixLS/zx-sizif-512#13]
Looks like there is one connection missing +3V3. PCB Editor is showing white line. 
Maybe I am missing something?

![This is an image](https://web.embeddedsoft.ca/missing.png)

R.

**Comment by UzixLS** [comment]
These 2 pins are connected internally in 1117 ldo. Unfortunately there is no way to tell Kicad "dont worry, its okay".

**Comment by AmiManga** [comment]
Got it. I was just checking. :) 
Awesome project btw. Great schematics!
