### ISSUE TITLE
Link for Harlequin

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [UzixLS/zx-sizif-512#2]
It would be nice to link to Don Superfo's Harlequin listing @ Sell My Retro here: (https://www.sellmyretro.com/offer/details/superfo-harlequin-128-zx-spectrum-128k-clone-new-version-4a-pcb-48417)
 
It also has a link to the schematics, etc.
 
 This way he will both be credited and possibly earn a buck for all of his work.

**Comment by UzixLS** [comment]
Added link to facebook group.
a785ff44d2d07241bd08f201daa745f8490761d9
