### ISSUE TITLE
Не работает клавиатура PS/2.

### ISSUE THREAD

**Issue by Alex-TV** [UzixLS/zx-sizif-512#3]
Собрал плату, подключил клавиатуру PS/2. При нажатии на клавиши нет реакции. Осциллографом проверил, сигналы от клавиатуры идут, после транзисторов тоже есть сигналы. Реакции на клавиатуру нет.

**Comment by UzixLS** [comment]
В прошивке ПЛИС ещё не реализовано.

**Comment by Alex-TV** [comment]
Понял, спасибо, буду ждать.

**Comment by UzixLS** [comment]
Finally released in ee1f05f1f38bb661430069a9865b5a2dc1e8d80a
