### ISSUE TITLE
cpld.rev.D.pof PCB ref D

### ISSUE THREAD

**Issue by Tomek474** [UzixLS/zx-sizif-512#30]
Hello, 
I have a problem with cpld.rev.D.pof batch dated 03.04.2023, AY is not working. AY in tests is not detected and the thanks is a terrible noise.

Batch cpld.rev.D.pof dated 30.08.2022 works correctly AY

What is the problem ? has something changed in the wiring diagram ?

Greetings very much

**Comment by UzixLS** [comment]
Where did you get all these files from?
Official pof files located at https://github.com/UzixLS/zx-sizif-512/releases , and there is no 03.04.2023 and 30.08.2022 releases.

**Comment by Tomek474** [comment]
[AY_cpld.rev.D.zip](https://github.com/UzixLS/zx-sizif-512/files/11152849/AY_cpld.rev.D.zip)

I downloaded the file from GITHUB once when there was no E version yet
and now I noticed that there is a newer pof when there is an E version

I have attached both files, maybe you will be able to recognize what version they are.

**Comment by Tomek474** [comment]
it seems to me that v20211204 is AY O.K
and v20221002 is AY BAD
something has changed in Altera software for D version

**Comment by Tomek474** [comment]
> Where did you get all these files from? Official pof and rom files located at https://github.com/UzixLS/zx-sizif-512/releases , and there is no 03.04.2023 and 30.08.2022 releases.

it's probably the dates of downloading files by me

**Comment by UzixLS** [comment]
I'm not sure why this is happening with your PCB as I haven't had any problems.
There is only one change around AY between v20211204 and v20221002. I reverted it, try this version: [rev_D.zip](https://github.com/UzixLS/zx-sizif-512/files/11155642/rev_D.zip)

**Comment by Tomek474** [comment]
I checked, AY works correctly behind the proposed insertion.
Thank you, is this file compatible with Firmware v20221002 ?

**Comment by UzixLS** [comment]
Yes, it's based on v20221002, but with reverted commit c26baf8e2c0e4bc6483cb4d750b199ec976fb1f5.
It fixes AY operations when turbo mode enabled, so I don't want to revert this commit in master branch.
I have no idea why it's breaking in your case, probably I should find more various AY chips to reproduce this problem.
Can I ask you to take photo of your AY and Z80?
