### ISSUE TITLE
SVF files

### ISSUE THREAD

**Issue by acid-maker** [UzixLS/zx-sizif-512#38]
Can you provide SVF files in release page. I have Mac and can program CPLD using OpenOCD, but I need SVF file, not POF file.

**Comment by acid-maker** [comment]
Can you provide SVF files in release page. I have Mac and can program CPLD using OpenOCD, but I need SVF file, not POF file.

**Comment by UzixLS** [comment]
For which pcb revision you need svf file?

**Comment by acid-maker** [comment]
I need SVF file for rev C1. I was able to create one myself using Quartus on Linux machine (it was very old version - 13.0). I've used OpenOCD on Mac and connected Sizif using USBBlaster (cheap version from Ali). Chip has been programmed correctly or at least it seemed so. I've also reprogrammed ROM chip. Everything seemed to be ok at the beginning, but my Sizif became very unstable. Previously it worked fine (I had very old firmware/ROM - the one without OSD), but now I'm unable to set 14Mhz - it freezes totally. 7MHz is max - then when I press right arrow it freezes. Also on standard 3.5MHz it works fine but only for couple of minutes and then it starts to work very unstable. I don't think that my SVF file causes that. I think that a wrong SVF file would rather brick the device. Any ideas? What to check?

Also it would be nice to have SVF files together with POF on your release page for all versions, also in the future. SVF file is "stupid" file with all JTAG "instructions" and therefore can be used with any JTAG programmer and any computer.

**Comment by UzixLS** [comment]
May be something wrong with your quartus setup? Try this files: 
[cpld firmware](https://github.com/UzixLS/zx-sizif-512/files/11902487/cpld.rev.C.fw-20221002.svf.zip)
[rom image](https://github.com/UzixLS/zx-sizif-512/releases/download/fw-20221002/rom.rev.C.rom)

I think it's good idea to officially provide svf file. I will do this for upcoming releases if I would confirm that SVF file works at least for you.

**Comment by UzixLS** [comment]
Closed due to inactivity
