### ISSUE TITLE
BOM in xlsx format (Sizif-512 E1)

### ISSUE THREAD

**Issue by Magnetrix** [UzixLS/zx-sizif-512#46]
Hello,
PCBWay requires the bom file in xlsx format...
Do you have such file ????

Thank you

**Comment by UzixLS** [comment]
There currently is no BOM file suitable for PCBWay assembly service. As far as I know, they need not just an xlsx file, but a specification with part numbers from their own catalog. It would take a lot of time to create it, and I have not interest to do this job.
But you are free to make it yourself using existing pdf or html BOM.

**Comment by Magnetrix** [comment]
Thanks anyway
