### ISSUE TITLE
Possible wrong connection in MIC jack (rev E1)

### ISSUE THREAD

**Issue by ZbeeGin** [UzixLS/zx-sizif-512#49]
I think the MIC jack has wrong _VID_MIC_ connection. The signal goes to the sleeve. 
I didn't see any TRRS Jack to 3xRCA AV cable, which have connection like this.

![sizif_e1_mic_jack_before](https://github.com/UzixLS/zx-sizif-512/assets/53860090/20009c10-1250-4667-a3e9-9280a6eb4ae0)

IMHO the _VID_MIC_ signal should be connected to the second ring, and GND to the sleeve. Like this:

![sizif_e1_mic_jack_after](https://github.com/UzixLS/zx-sizif-512/assets/53860090/34c48854-7d84-48fc-9b27-a9eaca5815d5)

**Comment by UzixLS** [comment]
Sizif (like all other my pcbs) uses same pinout as Raspberry Pi for AV cable.
I bought two cables in local store and had no any issues.

**Comment by ZbeeGin** [comment]
It seems there are two leading standards for AV Jack connection.
First: **OMTP** where tip is left audio, first ring is right audio, second ring is video(mic) and finally sleeve is the ground.
Second: **CTIA** where audio is the same as above, then second ring is ground and sleeve is the video(mic).

Unofrtunatelly I have only OMTP cable, because there are more of them on the market. At least in my country and nearest stores...
