### ISSUE TITLE
RGBS Jitters every few seconds. 

### ISSUE THREAD

**Issue by terenceang** [UzixLS/zx-sizif-512#8]
Hi, 

Once again thanks for this great project/

RGBS video jitters every few secs, it happens on both Sizif that I built. 
The is sent from the Sizif video out to a GBS=Control upscaler, image is nice, sharp and clean except for the jitters.
Video is in PAL mode and GBS-Control detects it correctly as PAL.
Jitter also doesn't happen with my other game consoles.
Here is a clip of the jitter - https://youtu.be/2h-cfVabX18

Thanks in advance. 
Terence

**Comment by UzixLS** [comment]
Hello
I've never dealt with GBS. I suppose there is some incompatibility with Pentagon video signal timings, which is going beyond PAL specifications. Can you check in 48K and 128K modes?

**Comment by terenceang** [comment]
Actually, The Pentagon timing is the only 1 that works, the others won't even lock.

**Comment by UzixLS** [comment]
Ouch, that's unexpected. 48K timings are best in terms of compatibility with TVs.
Are you using latest firmware? How GBS is connected to Sizif? Is your TV/Monitor supports 50Hz? Can you check frequency on 74HCU clock output? There is should be 28 MHz exactly.

**Comment by terenceang** [comment]
sadly, the clock is not 28Mhz exactly. it jitters at 27.78, 28.04, 28.09.

**Comment by terenceang** [comment]
It think I my 74HCU04 might be the problem, the China seller might have give me 74HC04. Let me double check. Thanks.

**Comment by terenceang** [comment]
is the clock out from 74HCU04N supposed to be a Square wave? mine is a sine wave. Ordering some 74HCU04 to try.

**Comment by UzixLS** [comment]
This may be caused by oscilloscope bandwidth limitation.

**Comment by terenceang** [comment]
I have a RIGOL DS1052E. will it measure 28Mhz properly?

**Comment by UzixLS** [comment]
No
